<?php
use App\Models\Branch;
use App\Support\Tenancy\CurrentCompany;
use Flux\Flux;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Support\Facades\Gate;
use Illuminate\Validation\Rule;
use Livewire\Attributes\Computed;
use Livewire\Attributes\Title;
use Livewire\Component;
use Livewire\WithPagination;

new #[Title('Sucursales')] class extends Component {
    use WithPagination;
    public string $search=''; public ?int $editingId=null; public string $code=''; public string $name=''; public string $address=''; public string $phone=''; public string $timezone=''; public bool $isActive=true;
    public function updatedSearch():void{$this->resetPage();}
    public function create():void{Gate::authorize('create',Branch::class);$this->resetForm();Flux::modal('branch-form')->show();}
    public function edit(int $id):void{$item=Branch::query()->findOrFail($id);Gate::authorize('update',$item);$this->editingId=$item->id;$this->code=$item->code;$this->name=$item->name;$this->address=$item->address??'';$this->phone=$item->phone??'';$this->timezone=$item->timezone??'';$this->isActive=$item->is_active;Flux::modal('branch-form')->show();}
    public function save():void{$companyId=app(CurrentCompany::class)->id();$item=$this->editingId?Branch::query()->findOrFail($this->editingId):null;Gate::authorize($item?'update':'create',$item??Branch::class);$data=$this->validate(['code'=>['required','string','max:50',Rule::unique('branches','code')->where('company_id',$companyId)->ignore($item)],'name'=>['required','string','max:255'],'address'=>['nullable','string'],'phone'=>['nullable','string','max:50'],'timezone'=>['nullable','timezone:all'],'isActive'=>['boolean']]);Branch::query()->updateOrCreate(['id'=>$item?->id],['company_id'=>$companyId,'code'=>$data['code'],'name'=>$data['name'],'address'=>filled($data['address'])?$data['address']:null,'phone'=>filled($data['phone'])?$data['phone']:null,'timezone'=>filled($data['timezone'])?$data['timezone']:null,'is_active'=>$data['isActive']]);Flux::modal('branch-form')->close();Flux::toast(variant:'success',text:$item?'Sucursal actualizada.':'Sucursal creada.');$this->resetForm();}
    public function toggle(int $id):void{$item=Branch::query()->findOrFail($id);Gate::authorize('update',$item);$item->update(['is_active'=>!$item->is_active]);Flux::toast(variant:'success',text:'Estado actualizado.');}
    #[Computed]public function branches():LengthAwarePaginator{return Branch::query()->withCount('warehouses')->when($this->search,fn($q)=>$q->where(fn($n)=>$n->where('name','like','%'.$this->search.'%')->orWhere('code','like','%'.$this->search.'%')))->latest()->paginate(12);}
    private function resetForm():void{$this->reset(['editingId','code','name','address','phone','timezone']);$this->isActive=true;$this->resetValidation();}
}; ?>
<div class="flex w-full flex-col gap-6"><div class="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><flux:heading size="xl">Sucursales</flux:heading><flux:text>Ubicaciones operativas de la empresa.</flux:text></div>@can('create',App\Models\Branch::class)<flux:button variant="primary" icon="plus" wire:click="create">Nueva sucursal</flux:button>@endcan</div><flux:input wire:model.live.debounce.300ms="search" icon="magnifying-glass" placeholder="Buscar sucursal" class="max-w-md" /><div class="grid gap-4 md:grid-cols-2 xl:grid-cols-3">@forelse($this->branches as $branch)<flux:card wire:key="branch-{{ $branch->id }}"><div class="flex justify-between gap-4"><div><flux:heading>{{ $branch->name }}</flux:heading><flux:text>{{ $branch->code }}</flux:text></div><flux:badge :color="$branch->is_active?'green':'zinc'">{{ $branch->is_active?'Activa':'Inactiva' }}</flux:badge></div><div class="mt-4 grid gap-2 text-sm"><div>{{ $branch->address?:'Sin dirección' }}</div><div>{{ $branch->phone?:'Sin teléfono' }}</div><div>{{ $branch->warehouses_count }} almacén(es)</div></div><div class="mt-5 flex justify-end gap-2"><flux:button size="sm" variant="subtle" wire:click="edit({{ $branch->id }})">Editar</flux:button><flux:button size="sm" variant="subtle" wire:click="toggle({{ $branch->id }})" wire:confirm="¿Cambiar el estado?">{{ $branch->is_active?'Desactivar':'Activar' }}</flux:button></div></flux:card>@empty<flux:card class="md:col-span-2 xl:col-span-3"><div class="py-10 text-center"><flux:heading>No hay sucursales</flux:heading><flux:text>Crea una sucursal antes de registrar almacenes.</flux:text></div></flux:card>@endforelse</div>{{ $this->branches->links() }}<flux:modal name="branch-form" class="max-w-xl"><form wire:submit="save" class="space-y-5"><flux:heading size="lg">{{ $editingId?'Editar sucursal':'Nueva sucursal' }}</flux:heading><div class="grid gap-4 sm:grid-cols-2"><flux:input wire:model="code" label="Código" required /><flux:input wire:model="name" label="Nombre" required /></div><flux:textarea wire:model="address" label="Dirección" /><flux:input wire:model="phone" label="Teléfono" /><flux:input wire:model="timezone" label="Zona horaria (opcional)" placeholder="America/La_Paz" /><flux:switch wire:model="isActive" label="Activa" /><div class="flex justify-end gap-3"><flux:modal.close><flux:button variant="ghost">Cancelar</flux:button></flux:modal.close><flux:button type="submit" variant="primary">Guardar</flux:button></div></form></flux:modal></div>
