<?php
use App\Models\Branch;
use App\Models\Warehouse;
use App\Support\Tenancy\CurrentCompany;
use Flux\Flux;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Support\Facades\Gate;
use Illuminate\Validation\Rule;
use Livewire\Attributes\Computed;
use Livewire\Attributes\Title;
use Livewire\Component;
use Livewire\WithPagination;

new #[Title('Almacenes')] class extends Component {
    use WithPagination;
    public string $search=''; public ?int $editingId=null; public ?int $branchId=null; public string $code=''; public string $name=''; public bool $isActive=true;
    public function updatedSearch():void{$this->resetPage();}
    public function create():void{Gate::authorize('create',Warehouse::class);$this->resetForm();Flux::modal('warehouse-form')->show();}
    public function edit(int $id):void{$item=Warehouse::query()->findOrFail($id);Gate::authorize('update',$item);$this->editingId=$item->id;$this->branchId=$item->branch_id;$this->code=$item->code;$this->name=$item->name;$this->isActive=$item->is_active;Flux::modal('warehouse-form')->show();}
    public function save():void{$companyId=app(CurrentCompany::class)->id();$item=$this->editingId?Warehouse::query()->findOrFail($this->editingId):null;Gate::authorize($item?'update':'create',$item??Warehouse::class);$data=$this->validate(['branchId'=>['required',Rule::exists('branches','id')->where('company_id',$companyId)],'code'=>['required','string','max:50',Rule::unique('warehouses','code')->where(fn($q)=>$q->where('company_id',$companyId)->where('branch_id',$this->branchId))->ignore($item)],'name'=>['required','string','max:255'],'isActive'=>['boolean']]);Warehouse::query()->updateOrCreate(['id'=>$item?->id],['company_id'=>$companyId,'branch_id'=>$data['branchId'],'code'=>$data['code'],'name'=>$data['name'],'is_active'=>$data['isActive']]);Flux::modal('warehouse-form')->close();Flux::toast(variant:'success',text:$item?'Almacén actualizado.':'Almacén creado.');$this->resetForm();}
    public function toggle(int $id):void{$item=Warehouse::query()->findOrFail($id);Gate::authorize('update',$item);$item->update(['is_active'=>!$item->is_active]);Flux::toast(variant:'success',text:'Estado actualizado.');}
    #[Computed]public function warehouses():LengthAwarePaginator{return Warehouse::query()->with('branch:id,name')->withCount('stockBalances')->when($this->search,fn($q)=>$q->where(fn($n)=>$n->where('name','like','%'.$this->search.'%')->orWhere('code','like','%'.$this->search.'%')))->latest()->paginate(12);}
    #[Computed]public function branches(){return Branch::query()->where('is_active',true)->orderBy('name')->get(['id','name']);}
    private function resetForm():void{$this->reset(['editingId','branchId','code','name']);$this->isActive=true;$this->resetValidation();}
}; ?>
<div class="flex w-full flex-col gap-6"><div class="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><flux:heading size="xl">Almacenes</flux:heading><flux:text>Espacios físicos donde se controla el inventario.</flux:text></div>@can('create',App\Models\Warehouse::class)<flux:button variant="primary" icon="plus" wire:click="create">Nuevo almacén</flux:button>@endcan</div><flux:input wire:model.live.debounce.300ms="search" icon="magnifying-glass" placeholder="Buscar almacén" class="max-w-md" /><flux:card class="overflow-hidden p-0!"><div class="overflow-x-auto"><flux:table :paginate="$this->warehouses"><flux:table.columns><flux:table.column>Almacén</flux:table.column><flux:table.column>Sucursal</flux:table.column><flux:table.column>Productos con saldo</flux:table.column><flux:table.column>Estado</flux:table.column><flux:table.column></flux:table.column></flux:table.columns><flux:table.rows>@forelse($this->warehouses as $warehouse)<flux:table.row :key="$warehouse->id"><flux:table.cell variant="strong">{{ $warehouse->name }}<flux:text size="sm">{{ $warehouse->code }}</flux:text></flux:table.cell><flux:table.cell>{{ $warehouse->branch->name }}</flux:table.cell><flux:table.cell>{{ $warehouse->stock_balances_count }}</flux:table.cell><flux:table.cell><flux:badge :color="$warehouse->is_active?'green':'zinc'">{{ $warehouse->is_active?'Activo':'Inactivo' }}</flux:badge></flux:table.cell><flux:table.cell><div class="flex justify-end gap-2"><flux:button size="sm" variant="subtle" wire:click="edit({{ $warehouse->id }})">Editar</flux:button><flux:button size="sm" variant="subtle" wire:click="toggle({{ $warehouse->id }})" wire:confirm="¿Cambiar el estado?">{{ $warehouse->is_active?'Desactivar':'Activar' }}</flux:button></div></flux:table.cell></flux:table.row>@empty<flux:table.row><flux:table.cell colspan="5"><div class="py-10 text-center"><flux:heading>No hay almacenes</flux:heading><flux:text>Crea una sucursal y luego tu primer almacén.</flux:text></div></flux:table.cell></flux:table.row>@endforelse</flux:table.rows></flux:table></div></flux:card><flux:modal name="warehouse-form" class="max-w-lg"><form wire:submit="save" class="space-y-5"><flux:heading size="lg">{{ $editingId?'Editar almacén':'Nuevo almacén' }}</flux:heading><flux:select wire:model="branchId" label="Sucursal" required><flux:select.option value="">Seleccionar</flux:select.option>@foreach($this->branches as $branch)<flux:select.option :value="$branch->id">{{ $branch->name }}</flux:select.option>@endforeach</flux:select><div class="grid gap-4 sm:grid-cols-2"><flux:input wire:model="code" label="Código" required /><flux:input wire:model="name" label="Nombre" required /></div><flux:switch wire:model="isActive" label="Activo" /><div class="flex justify-end gap-3"><flux:modal.close><flux:button variant="ghost">Cancelar</flux:button></flux:modal.close><flux:button type="submit" variant="primary">Guardar</flux:button></div></form></flux:modal></div>
