<?php
use App\Models\Unit;
use App\Support\Tenancy\CurrentCompany;
use Flux\Flux;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Support\Facades\Gate;
use Illuminate\Validation\Rule;
use Livewire\Attributes\Computed;
use Livewire\Attributes\Title;
use Livewire\Component;
use Livewire\WithPagination;

new #[Title('Unidades')] class extends Component {
    use WithPagination;
    public string $search=''; public ?int $editingId=null; public string $code=''; public string $name=''; public string $symbol=''; public int $decimalPlaces=0; public bool $isActive=true;
    public function updatedSearch():void{$this->resetPage();}
    public function create():void{Gate::authorize('create',Unit::class);$this->resetForm();Flux::modal('unit-form')->show();}
    public function edit(int $id):void{$item=Unit::query()->findOrFail($id);Gate::authorize('update',$item);$this->editingId=$item->id;$this->code=$item->code;$this->name=$item->name;$this->symbol=$item->symbol;$this->decimalPlaces=$item->decimal_places;$this->isActive=$item->is_active;Flux::modal('unit-form')->show();}
    public function save():void{$companyId=app(CurrentCompany::class)->id();$item=$this->editingId?Unit::query()->findOrFail($this->editingId):null;Gate::authorize($item?'update':'create',$item??Unit::class);$data=$this->validate(['code'=>['required','string','max:30',Rule::unique('units','code')->where('company_id',$companyId)->ignore($item)],'name'=>['required','string','max:255'],'symbol'=>['required','string','max:20'],'decimalPlaces'=>['required','integer','between:0,6'],'isActive'=>['boolean']]);Unit::query()->updateOrCreate(['id'=>$item?->id],['company_id'=>$companyId,'code'=>$data['code'],'name'=>$data['name'],'symbol'=>$data['symbol'],'decimal_places'=>$data['decimalPlaces'],'is_active'=>$data['isActive']]);Flux::modal('unit-form')->close();Flux::toast(variant:'success',text:$item?'Unidad actualizada.':'Unidad creada.');$this->resetForm();}
    public function toggle(int $id):void{$item=Unit::query()->findOrFail($id);Gate::authorize($item->is_active?'deactivate':'update',$item);$item->update(['is_active'=>!$item->is_active]);Flux::toast(variant:'success',text:'Estado actualizado.');}
    #[Computed]public function units():LengthAwarePaginator{return Unit::query()->when($this->search,fn($q)=>$q->where(fn($n)=>$n->where('name','like','%'.$this->search.'%')->orWhere('code','like','%'.$this->search.'%')->orWhere('symbol','like','%'.$this->search.'%')))->latest()->paginate(12);}
    private function resetForm():void{$this->reset(['editingId','code','name','symbol']);$this->decimalPlaces=0;$this->isActive=true;$this->resetValidation();}
}; ?>
<div class="flex w-full flex-col gap-6"><div class="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><flux:heading size="xl">Unidades</flux:heading><flux:text>Define cómo se expresan las cantidades. Sin conversiones por ahora.</flux:text></div>@can('create',App\Models\Unit::class)<flux:button variant="primary" icon="plus" wire:click="create">Nueva unidad</flux:button>@endcan</div><flux:input wire:model.live.debounce.300ms="search" icon="magnifying-glass" placeholder="Buscar unidad" class="max-w-md" /><flux:card class="overflow-hidden p-0!"><div class="overflow-x-auto"><flux:table :paginate="$this->units"><flux:table.columns><flux:table.column>Unidad</flux:table.column><flux:table.column>Símbolo</flux:table.column><flux:table.column>Decimales</flux:table.column><flux:table.column>Estado</flux:table.column><flux:table.column></flux:table.column></flux:table.columns><flux:table.rows>@forelse($this->units as $unit)<flux:table.row :key="$unit->id"><flux:table.cell variant="strong">{{ $unit->name }}<flux:text size="sm">{{ $unit->code }}</flux:text></flux:table.cell><flux:table.cell>{{ $unit->symbol }}</flux:table.cell><flux:table.cell>{{ $unit->decimal_places }}</flux:table.cell><flux:table.cell><flux:badge :color="$unit->is_active?'green':'zinc'">{{ $unit->is_active?'Activa':'Inactiva' }}</flux:badge></flux:table.cell><flux:table.cell><div class="flex justify-end gap-2"><flux:button size="sm" variant="subtle" wire:click="edit({{ $unit->id }})">Editar</flux:button><flux:button size="sm" variant="subtle" wire:click="toggle({{ $unit->id }})" wire:confirm="¿Cambiar el estado?">{{ $unit->is_active?'Desactivar':'Activar' }}</flux:button></div></flux:table.cell></flux:table.row>@empty<flux:table.row><flux:table.cell colspan="5"><div class="py-10 text-center"><flux:heading>No hay unidades</flux:heading><flux:text>Crea UND, DOC, M o KG para comenzar.</flux:text></div></flux:table.cell></flux:table.row>@endforelse</flux:table.rows></flux:table></div></flux:card><flux:modal name="unit-form" class="max-w-lg"><form wire:submit="save" class="space-y-5"><flux:heading size="lg">{{ $editingId?'Editar unidad':'Nueva unidad' }}</flux:heading><div class="grid gap-4 sm:grid-cols-2"><flux:input wire:model="code" label="Código" placeholder="UND" required /><flux:input wire:model="symbol" label="Símbolo" placeholder="UND" required /></div><flux:input wire:model="name" label="Nombre" placeholder="Unidad" required /><flux:input wire:model="decimalPlaces" type="number" min="0" max="6" label="Decimales" /><flux:switch wire:model="isActive" label="Activa" /><div class="flex justify-end gap-3"><flux:modal.close><flux:button variant="ghost">Cancelar</flux:button></flux:modal.close><flux:button type="submit" variant="primary">Guardar</flux:button></div></form></flux:modal></div>
